# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Anudeep\Projects\V2F Classifier\UI\main A02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import cv2


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1400, 800)
        Dialog.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(1010, 730, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(250, -50, 20, 1001))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 20, 221, 135))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_path_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.input_path_browse.setObjectName("input_path_browse")
        self.horizontalLayout.addWidget(self.input_path_browse)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.uploaded_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.uploaded_2.setText("")
        self.uploaded_2.setCheckable(True)
        self.uploaded_2.setObjectName("uploaded_2")
        self.gridLayout.addWidget(self.uploaded_2, 1, 1, 1, 1)
        self.extract = QtWidgets.QPushButton(self.layoutWidget)
        self.extract.setObjectName("extract")
        self.gridLayout.addWidget(self.extract, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.output_path_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.output_path_browse.setObjectName("output_path_browse")
        self.horizontalLayout_2.addWidget(self.output_path_browse)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.uploaded_1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.uploaded_1.setText("")
        self.uploaded_1.setCheckable(True)
        self.uploaded_1.setChecked(False)
        self.uploaded_1.setObjectName("uploaded_1")
        self.gridLayout.addWidget(self.uploaded_1, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 450, 53, 16))
        self.label_3.setObjectName("label_3")
        self.no_of_frames_label = QtWidgets.QLabel(Dialog)
        self.no_of_frames_label.setGeometry(QtCore.QRect(32, 203, 113, 16))
        self.no_of_frames_label.setObjectName("no_of_frames_label")
        self.done = QtWidgets.QLabel(Dialog)
        self.done.setGeometry(QtCore.QRect(180, 170, 55, 16))
        self.done.setText("")
        self.done.setObjectName("done")
        self.no_of_frames = QtWidgets.QLabel(Dialog)
        self.no_of_frames.setGeometry(QtCore.QRect(180, 203, 55, 16))
        self.no_of_frames.setObjectName("no_of_frames")
        self.advanced = QtWidgets.QCheckBox(Dialog)
        self.advanced.setGeometry(QtCore.QRect(30, 170, 81, 20))
        self.advanced.setObjectName("advanced")
        self.size_of_image_label = QtWidgets.QLabel(Dialog)
        self.size_of_image_label.setGeometry(QtCore.QRect(32, 228, 87, 16))
        self.size_of_image_label.setObjectName("size_of_image_label")
        self.size_of_image = QtWidgets.QLabel(Dialog)
        self.size_of_image.setGeometry(QtCore.QRect(180, 228, 55, 16))
        self.size_of_image.setObjectName("size_of_image")
        self.est_projec_size_label = QtWidgets.QLabel(Dialog)
        self.est_projec_size_label.setGeometry(QtCore.QRect(32, 253, 135, 16))
        self.est_projec_size_label.setObjectName("est_projec_size_label")
        self.est_project_size = QtWidgets.QLabel(Dialog)
        self.est_project_size.setGeometry(QtCore.QRect(180, 253, 55, 16))
        self.est_project_size.setObjectName("est_project_size")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 670, 221, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(25, 640, 70, 16))
        self.label_7.setObjectName("label_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 480, 221, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(20, 570, 221, 51))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.current_frame_label = QtWidgets.QLabel(Dialog)
        self.current_frame_label.setGeometry(QtCore.QRect(32, 278, 90, 16))
        self.current_frame_label.setObjectName("current_frame_label")
        self.current_frame = QtWidgets.QLabel(Dialog)
        self.current_frame.setGeometry(QtCore.QRect(180, 278, 55, 16))
        self.current_frame.setObjectName("current_frame")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 540, 62, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


        #User Code
        self.input_path_browse.clicked.connect(self.input_path_browse_clicked)
        self.output_path_browse.clicked.connect(self.output_path_browse_clicked)
        self.extract.clicked.connect(self.Extract)
        self.advanced.stateChanged.connect(self.Advanced)




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "V2F Classifier"))
        self.label.setText(_translate("Dialog", "Input Path"))
        self.input_path_browse.setText(_translate("Dialog", "Browse"))
        self.extract.setText(_translate("Dialog", "Extract"))
        self.label_2.setText(_translate("Dialog", "Output Path"))
        self.output_path_browse.setText(_translate("Dialog", "Browse"))
        self.progressBar.setFormat(_translate("Dialog", "%p%"))
        self.label_3.setText(_translate("Dialog", "Input File"))
        self.no_of_frames_label.setText(_translate("Dialog", " "))
        self.no_of_frames.setText(_translate("Dialog", " "))
        self.advanced.setText(_translate("Dialog", "Advanced"))
        self.size_of_image_label.setText(_translate("Dialog", " "))
        self.size_of_image.setText(_translate("Dialog", " "))
        self.est_projec_size_label.setText(_translate("Dialog", " "))
        self.est_project_size.setText(_translate("Dialog", " "))
        self.label_7.setText(_translate("Dialog", "Errors"))
        self.current_frame_label.setText(_translate("Dialog", " "))
        self.current_frame.setText(_translate("Dialog", " "))
        self.label_4.setText(_translate("Dialog", "Output File"))



    def input_path_browse_clicked(self):
        file_name = QtWidgets.QFileDialog.getOpenFileNames(None, 'Browse Input File', '.')
        self.input_file_path = file_name[0][0]
        if self.input_file_path:
            self.uploaded_1.setChecked(True)
            self.textBrowser_2.setText(self.input_file_path)

    def output_path_browse_clicked(self):
        file_name = QtWidgets.QFileDialog.getExistingDirectory(None, 'Browse Input File', '.')
        self.output_file_path = file_name
        if self.output_file_path:
            self.uploaded_2.setChecked(True)
            self.textBrowser_4.setText(self.output_file_path)

    def Extract_details(self):
        if self.uploaded_1.checkState():
            vidcap = cv2.VideoCapture(self.input_file_path)
            self.vidcap = vidcap
            success,image = vidcap.read()
            self.count = 0
            self.total_frames = int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT))   
            self.width = vidcap.get(cv2.CAP_PROP_FRAME_WIDTH )
            self.height = vidcap.get(cv2.CAP_PROP_FRAME_HEIGHT )
            self.progressBar.setMinimum(0)
            self.progressBar.setMaximum(self.total_frames)

    def Extract(self):
        if self.uploaded_1.checkState() and self.uploaded_2.checkState():
            vidcap = cv2.VideoCapture(self.input_file_path)
            success,image = vidcap.read()
            self.count = 0
            self.total_frames = int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT))   
            self.width = vidcap.get(cv2.CAP_PROP_FRAME_WIDTH )
            self.height = vidcap.get(cv2.CAP_PROP_FRAME_HEIGHT )
            self.progressBar.setMinimum(0)
            self.progressBar.setMaximum(self.total_frames)
            while success:
                cv2.imwrite(self.output_file_path + f"frame{self.count}.jpg", image)     # save frame as JPEG file      
                success,image = vidcap.read()
                self.count += 1
                self.progressBar.setValue(self.count)
            self.done.setText("Done")
        else:
            if self.uploaded_1.checkState():
                self.textBrowser.setText("No output path was given")
            else:
                self.textBrowser.setText("No input file was given")

    def Advanced(self):
        try:
            if self.advanced.checkState() and self.input_file_path:
                self.no_of_frames_label.setText("Number of frames :")
                self.size_of_image_label.setText("Size of image :")
                self.est_projec_size_label.setText("Estimated project size :")


                self.Extract_details()
                self.no_of_frames.setText(str(self.total_frames))
                self.size_of_image.setText(str(int(self.height * self.width )) + " pixels")
                self.est_project_size.setText(str(int((self.total_frames * self.height * self.width * 2)/1e7)) + " mb")

                print("hi")
            else:
                self.no_of_frames_label.setText("")
                self.size_of_image_label.setText("")
                self.est_projec_size_label.setText("")
        except:
            self.textBrowser.setText("No input file was selected or file with wrong format is selected")
                


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
