# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Anudeep\Projects\V2F Classifier\UI\main A02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
import glob
import os
import shutil

class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1400, 800)
        Dialog.setStyleSheet("")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(250, -50, 20, 1001))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 20, 221, 135))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_path_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.input_path_browse.setObjectName("input_path_browse")
        self.horizontalLayout.addWidget(self.input_path_browse)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.uploaded_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.uploaded_2.setText("")
        self.uploaded_2.setCheckable(True)
        self.uploaded_2.setObjectName("uploaded_2")
        self.gridLayout.addWidget(self.uploaded_2, 1, 1, 1, 1)
        self.extract = QtWidgets.QPushButton(self.layoutWidget)
        self.extract.setObjectName("extract")
        self.gridLayout.addWidget(self.extract, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.output_path_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.output_path_browse.setObjectName("output_path_browse")
        self.horizontalLayout_2.addWidget(self.output_path_browse)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.uploaded_1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.uploaded_1.setText("")
        self.uploaded_1.setCheckable(True)
        self.uploaded_1.setChecked(False)
        self.uploaded_1.setObjectName("uploaded_1")
        self.gridLayout.addWidget(self.uploaded_1, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 450, 53, 16))
        self.label_3.setObjectName("label_3")
        self.no_of_frames_label = QtWidgets.QLabel(Dialog)
        self.no_of_frames_label.setGeometry(QtCore.QRect(32, 203, 113, 16))
        self.no_of_frames_label.setText("")
        self.no_of_frames_label.setObjectName("no_of_frames_label")
        self.done = QtWidgets.QLabel(Dialog)
        self.done.setGeometry(QtCore.QRect(180, 170, 55, 16))
        self.done.setText("")
        self.done.setObjectName("done")
        self.no_of_frames = QtWidgets.QLabel(Dialog)
        self.no_of_frames.setGeometry(QtCore.QRect(180, 203, 55, 16))
        self.no_of_frames.setText("")
        self.no_of_frames.setObjectName("no_of_frames")
        self.advanced = QtWidgets.QCheckBox(Dialog)
        self.advanced.setGeometry(QtCore.QRect(30, 170, 81, 20))
        self.advanced.setObjectName("advanced")
        self.size_of_image_label = QtWidgets.QLabel(Dialog)
        self.size_of_image_label.setGeometry(QtCore.QRect(32, 228, 87, 16))
        self.size_of_image_label.setText("")
        self.size_of_image_label.setObjectName("size_of_image_label")
        self.size_of_image = QtWidgets.QLabel(Dialog)
        self.size_of_image.setGeometry(QtCore.QRect(180, 228, 55, 16))
        self.size_of_image.setText("")
        self.size_of_image.setObjectName("size_of_image")
        self.est_projec_size_label = QtWidgets.QLabel(Dialog)
        self.est_projec_size_label.setGeometry(QtCore.QRect(32, 253, 135, 16))
        self.est_projec_size_label.setText("")
        self.est_projec_size_label.setObjectName("est_projec_size_label")
        self.est_project_size = QtWidgets.QLabel(Dialog)
        self.est_project_size.setGeometry(QtCore.QRect(180, 253, 55, 16))
        self.est_project_size.setText("")
        self.est_project_size.setObjectName("est_project_size")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 670, 221, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(25, 640, 70, 16))
        self.label_7.setObjectName("label_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 480, 221, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(20, 570, 221, 51))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.current_frame_label = QtWidgets.QLabel(Dialog)
        self.current_frame_label.setGeometry(QtCore.QRect(32, 278, 90, 16))
        self.current_frame_label.setText("")
        self.current_frame_label.setObjectName("current_frame_label")
        self.current_frame = QtWidgets.QLabel(Dialog)
        self.current_frame.setGeometry(QtCore.QRect(180, 278, 55, 16))
        self.current_frame.setText("")
        self.current_frame.setObjectName("current_frame")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 540, 62, 16))
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(260, 650, 1171, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(470, 670, 31, 28))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(280, 710, 221, 51))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(310, 60, 741, 531))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:\\Users\\Anudeep\\Projects\\V2F Classifier\\UI\\../../../Pictures/Wallpapers/froppy.jpeg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.undo = QtWidgets.QPushButton(Dialog)
        self.undo.setGeometry(QtCore.QRect(1230, 600, 121, 31))
        self.undo.setObjectName("undo")
        self.input_path_browse_2 = QtWidgets.QPushButton(Dialog)
        self.input_path_browse_2.setGeometry(QtCore.QRect(377, 670, 87, 28))
        self.input_path_browse_2.setObjectName("input_path_browse_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(280, 675, 58, 16))
        self.label_5.setObjectName("label_5")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(1110, 675, 262, 96))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_6 = QtWidgets.QLabel(self.splitter)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.widget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_8 = QtWidgets.QLabel(self.splitter_2)
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(1100, 380, 251, 211))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 3, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 4, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_3.addWidget(self.pushButton_13, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


        #User Code
        self.input_path_browse.clicked.connect(self.input_path_browse_clicked)
        self.output_path_browse.clicked.connect(self.output_path_browse_clicked)
        self.extract.clicked.connect(self.Extract)
        self.advanced.stateChanged.connect(self.Advanced)
        self.input_path_browse_2.clicked.connect(self.browse_2)
        self.pushButton.clicked.connect(self.copy_path)
        self.pushButton_2.clicked.connect(self.set_names)
        self.pushButton_3.clicked.connect(self.start)

        self.pushButton_4.clicked.connect(self.c_1)
        self.pushButton_5.clicked.connect(self.c_2)
        self.pushButton_6.clicked.connect(self.c_3)
        self.pushButton_7.clicked.connect(self.c_4)
        self.pushButton_8.clicked.connect(self.c_5)
        self.pushButton_9.clicked.connect(self.c_6)
        self.pushButton_10.clicked.connect(self.c_7)
        self.pushButton_11.clicked.connect(self.c_8)
        self.pushButton_12.clicked.connect(self.c_9)
        self.pushButton_13.clicked.connect(self.c_10)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "V2F Classifier"))
        self.label.setText(_translate("Dialog", "Input Path"))
        self.input_path_browse.setText(_translate("Dialog", "Browse"))
        self.extract.setText(_translate("Dialog", "Extract"))
        self.label_2.setText(_translate("Dialog", "Output Path"))
        self.output_path_browse.setText(_translate("Dialog", "Browse"))
        self.progressBar.setFormat(_translate("Dialog", "%p%"))
        self.label_3.setText(_translate("Dialog", "Input File"))
        self.advanced.setText(_translate("Dialog", "Advanced"))
        self.label_7.setText(_translate("Dialog", "Errors"))
        self.label_4.setText(_translate("Dialog", "Output File"))
        self.pushButton.setText(_translate("Dialog", ">>"))
        self.undo.setText(_translate("Dialog", "Undo"))
        self.input_path_browse_2.setText(_translate("Dialog", "Browse"))
        self.label_5.setText(_translate("Dialog", "Input Path"))
        self.label_6.setText(_translate("Dialog", "Number of categories"))
        self.label_8.setText(_translate("Dialog", "Category names"))
        self.pushButton_2.setText(_translate("Dialog", "Set Names"))
        self.pushButton_3.setText(_translate("Dialog", "Start"))
        self.pushButton_4.setText(_translate("Dialog", " "))
        self.pushButton_5.setText(_translate("Dialog", " "))
        self.pushButton_6.setText(_translate("Dialog", " "))
        self.pushButton_7.setText(_translate("Dialog", " "))
        self.pushButton_8.setText(_translate("Dialog", " "))
        self.pushButton_9.setText(_translate("Dialog", " "))
        self.pushButton_10.setText(_translate("Dialog", " "))
        self.pushButton_11.setText(_translate("Dialog", " "))
        self.pushButton_12.setText(_translate("Dialog", " "))
        self.pushButton_13.setText(_translate("Dialog", " "))


    def input_path_browse_clicked(self):
        file_name = QtWidgets.QFileDialog.getOpenFileNames(None, 'Browse Input File', '.')
        self.input_file_path = file_name[0][0]
        if self.input_file_path:
            self.uploaded_1.setChecked(True)
            self.textBrowser_2.setText(self.input_file_path)

    def output_path_browse_clicked(self):
        file_name = QtWidgets.QFileDialog.getExistingDirectory(None, 'Browse Input File', '.')
        self.output_file_path = file_name
        if self.output_file_path:
            self.uploaded_2.setChecked(True)
            self.textBrowser_4.setText(self.output_file_path)

    def Extract_details(self):
        if self.uploaded_1.checkState():
            vidcap = cv2.VideoCapture(self.input_file_path)
            self.vidcap = vidcap
            success,image = vidcap.read()
            self.count = 0
            self.total_frames = int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT))   
            self.width = vidcap.get(cv2.CAP_PROP_FRAME_WIDTH )
            self.height = vidcap.get(cv2.CAP_PROP_FRAME_HEIGHT )
            self.progressBar.setMinimum(0)
            self.progressBar.setMaximum(self.total_frames)

    def Extract(self):
        if self.uploaded_1.checkState() and self.uploaded_2.checkState():
            vidcap = cv2.VideoCapture(self.input_file_path)
            success,image = vidcap.read()
            self.count = 0
            self.total_frames = int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT))   
            self.width = vidcap.get(cv2.CAP_PROP_FRAME_WIDTH )
            self.height = vidcap.get(cv2.CAP_PROP_FRAME_HEIGHT )
            self.progressBar.setMinimum(0)
            self.progressBar.setMaximum(self.total_frames)
            while success:
                cv2.imwrite(self.output_file_path + f"\\frame{self.count}.jpg", image)     # save frame as JPEG file      
                success,image = vidcap.read()
                self.count += 1
                self.progressBar.setValue(self.count)
            self.done.setText("Done")
        else:
            if self.uploaded_1.checkState():
                self.textBrowser.setText("No output path was given")
            else:
                self.textBrowser.setText("No input file was given")

    def Advanced(self):
        try:
            if self.advanced.checkState() and self.input_file_path:
                self.no_of_frames_label.setText("Number of frames :")
                self.size_of_image_label.setText("Size of image :")
                self.est_projec_size_label.setText("Estimated project size :")


                self.Extract_details()
                self.no_of_frames.setText(str(self.total_frames))
                self.size_of_image.setText(str(int(self.height * self.width )) + " pixels")
                self.est_project_size.setText(str(int((self.total_frames * self.height * self.width * 2)/1e7)) + " mb")

            else:
                self.no_of_frames_label.setText("")
                self.size_of_image_label.setText("")
                self.est_projec_size_label.setText("")
        except:
            self.textBrowser.setText("No input file was selected or file with wrong format is selected")
    

    def browse_2(self):
        file_name = QtWidgets.QFileDialog.getExistingDirectory(None, 'Browse Input File', '.')
        if file_name:
            self.textBrowser_3.setText(file_name)
            names = glob.glob(file_name+"/"+"*.jpg")
            self.input_file_path_2 = file_name
            self.all_names = names

    def copy_path(self):
        try:
            self.textBrowser_3.setText(self.output_file_path)
            file_name = os.path.abspath(os.getcwd())
            names = glob.glob(file_name+"/"+"*.jpg")
            self.input_file_path_2 = file_name
        except:
            self.textBrowser.setText("No output folder provided")


    def set_names(self):
        try:
            if self.lineEdit.text():
                self.textBrowser.setText("")

                self.num_cat = self.lineEdit.text()


                sDialog = QtWidgets.QDialog()
                ui = sub_Dialog()
                ui.setupUi(sDialog)
                sDialog.show()
                sDialog.exec_()
                print(cat_names_list)
            
            else:
                self.textBrowser.setText("Type number of categories")


        except:
            self.textBrowser.setText("Type number of categories")


    def start(self):
            categories = []
            for i in cat_names_list:
                if i:
                    categories.append(i)
            
            size = len(categories)

            if size != int(self.lineEdit.text()):
                self.textBrowser.setText("Entered wrong number of categories")
            else:
                self.textBrowser.setText("")
            

                for i in range(size):
                    #print(categories[i])
                    exec(f"self.pushButton_{str(4+i)}.setText('{categories[i]}')")

                    if not os.path.exists(self.input_file_path_2+'/'+categories[i]):
                        print("No folder exists")
                        os.mkdir(self.input_file_path_2 + '/' + categories[i])

                self.categories = categories                    
                self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))
        
        



    def c_1(self):
        if self.categories[0]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[0])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))

    
    def c_2(self):
        if self.categories[1]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[1])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))

    def c_3(self):
        if self.categories[2]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[2])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))

    def c_4(self):
        if self.categories[3]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[3])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))

    def c_5(self):
        if self.categories[4]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[4])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))

    def c_6(self):
        if self.categories[5]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[5])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))

    def c_7(self):
        if self.categories[6]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[6])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))

    def c_8(self):
        if self.categories[7]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[7])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))

    def c_9(self):
        if self.categories[8]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[8])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))

    def c_10(self):
        if self.categories[9]:
            img = self.all_names.pop(0)
            shutil.move(img, self.input_file_path_2 + '/' + self.categories[9])
            self.label_9.setPixmap(QtGui.QPixmap(self.all_names[0]))





class sub_Dialog(object):
    def __init__(self):
        super().__init__()


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(277, 426)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(150, 370, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 30, 219, 325))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_6.addWidget(self.lineEdit_6)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_7.addWidget(self.lineEdit_7)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_8.addWidget(self.lineEdit_8)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_9.addWidget(self.lineEdit_9)
        self.gridLayout.addLayout(self.horizontalLayout_9, 8, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_10.addWidget(self.lineEdit_10)
        self.gridLayout.addLayout(self.horizontalLayout_10, 9, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton.clicked.connect(self.cat_names)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Set Category names"))
        self.pushButton.setText(_translate("Dialog", "Done"))
        self.label.setText(_translate("Dialog", "Category 1 :"))
        self.label_2.setText(_translate("Dialog", "Category 2 :"))
        self.label_3.setText(_translate("Dialog", "Category 3 :"))
        self.label_4.setText(_translate("Dialog", "Category 4 :"))
        self.label_5.setText(_translate("Dialog", "Category 5 :"))
        self.label_6.setText(_translate("Dialog", "Category 6 :"))
        self.label_7.setText(_translate("Dialog", "Category 7 :"))
        self.label_8.setText(_translate("Dialog", "Category 8 :"))
        self.label_9.setText(_translate("Dialog", "Category 9 :"))
        self.label_10.setText(_translate("Dialog", "Category 10 :"))

    def cat_names(self):
        global cat_names_list
        cat_names_list = [self.lineEdit.text(),
                                self.lineEdit_2.text(),
                                self.lineEdit_3.text(),
                                self.lineEdit_4.text(),
                                self.lineEdit_5.text(),
                                self.lineEdit_6.text(),
                                self.lineEdit_7.text(),
                                self.lineEdit_8.text(),
                                self.lineEdit_9.text(),
                                self.lineEdit_10.text()
                                ]




    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
