# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Anudeep\Projects\V2F Classifier\UI\main A02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

import cv2

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1400, 800)
        Dialog.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(1010, 730, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(250, -70, 20, 1001))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 20, 221, 135))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_path_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.input_path_browse.setObjectName("input_path_browse")
        self.horizontalLayout.addWidget(self.input_path_browse)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.uploaded_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.uploaded_2.setText("")
        self.uploaded_2.setCheckable(True)
        self.uploaded_2.setObjectName("uploaded_2")
        self.gridLayout.addWidget(self.uploaded_2, 1, 1, 1, 1)
        self.extract = QtWidgets.QPushButton(self.layoutWidget)
        self.extract.setObjectName("extract")
        self.gridLayout.addWidget(self.extract, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.output_path_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.output_path_browse.setObjectName("output_path_browse")
        self.horizontalLayout_2.addWidget(self.output_path_browse)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.uploaded_1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.uploaded_1.setText("")
        self.uploaded_1.setCheckable(True)
        self.uploaded_1.setChecked(False)
        self.uploaded_1.setObjectName("uploaded_1")
        self.gridLayout.addWidget(self.uploaded_1, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        #User Code
        self.input_path_browse.clicked.connect(self.input_path_browse_clicked)
        self.output_path_browse.clicked.connect(self.output_path_browse_clicked)
        self.extract.clicked.connect(self.Extract)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "V2F Classifier"))
        self.label.setText(_translate("Dialog", "Input Path"))
        self.input_path_browse.setText(_translate("Dialog", "Browse"))
        self.extract.setText(_translate("Dialog", "Extract"))
        self.label_2.setText(_translate("Dialog", "Output Path"))
        self.output_path_browse.setText(_translate("Dialog", "Browse"))
        self.progressBar.setFormat(_translate("Dialog", "%p%"))

    def input_path_browse_clicked(self):
        file_name = QFileDialog.getOpenFileNames(None, 'Browse Input File', '.')
        self.input_file_path = file_name[0][0]
        if self.input_file_path:
            self.uploaded_1.setChecked(True)

    def output_path_browse_clicked(self):
        file_name = QFileDialog.getExistingDirectory(None, 'Browse Input File', '.')
        self.output_file_path = file_name
        if self.output_file_path:
            self.uploaded_2.setChecked(True)

    def Extract(self):
        if self.uploaded_1.checkState and self.uploaded_2.checkState:
            vidcap = cv2.VideoCapture(self.input_file_path)
            success,image = vidcap.read()
            self.count = 0
            self.total_frames = int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT))
            self.progressBar.setMinimum(0)
            self.progressBar.setMaximum(self.total_frames)
            while success:
                cv2.imwrite(self.output_file_path + f"frame{self.count}.jpg", image)     # save frame as JPEG file      
                success,image = vidcap.read()
                self.count += 1
                self.progressBar.setValue(self.count)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
