# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Anudeep\Projects\V2F Classifier\UI\main A02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1400, 800)
        Dialog.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(1010, 730, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(250, -70, 20, 1001))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(23, 22, 231, 135))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_path_browse = QtWidgets.QPushButton(self.widget)
        self.input_path_browse.setObjectName("input_path_browse")
        self.horizontalLayout.addWidget(self.input_path_browse)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.uploaded_3 = QtWidgets.QLabel(self.widget)
        self.uploaded_3.setText("")
        self.uploaded_3.setObjectName("uploaded_3")
        self.gridLayout.addWidget(self.uploaded_3, 0, 1, 2, 1)
        self.uploaded_1 = QtWidgets.QLabel(self.widget)
        self.uploaded_1.setText("")
        self.uploaded_1.setObjectName("uploaded_1")
        self.gridLayout.addWidget(self.uploaded_1, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.output_path_browse = QtWidgets.QPushButton(self.widget)
        self.output_path_browse.setObjectName("output_path_browse")
        self.horizontalLayout_2.addWidget(self.output_path_browse)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.extract = QtWidgets.QPushButton(self.widget)
        self.extract.setObjectName("extract")
        self.gridLayout.addWidget(self.extract, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        #User Code
        self.input_path_browse.clicked.connect(self.btn_input_path_browse)
        self.output_path_browse.clicked.connect(self.btn_output_path_browse)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "V2F Classifier"))
        self.label.setText(_translate("Dialog", "Input Path"))
        self.input_path_browse.setText(_translate("Dialog", "Browse"))
        self.label_2.setText(_translate("Dialog", "Output Path"))
        self.output_path_browse.setText(_translate("Dialog", "Browse"))
        self.extract.setText(_translate("Dialog", "Extract"))
        self.progressBar.setFormat(_translate("Dialog", "%p%"))

    def btn_input_path_browse(self):
        print("clicked")
        self.uploaded_1.setText("✓")

    def btn_output_path_browse(self):
        print("clicked")
        self.uploaded_3.setText("✓")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
